#spring.graphql.graphiql.enabled=true
#spring.graphql.graphiql.path=/graphiql
#spring.graphql.websocket.path=/subscriptions
#spring.graphql.cors.allowed-origins=*
#spring.graphql.cors.allowed-methods=GET,POST
#management.endpoints.web.exposure.include=health,metrics,info

spring.mvc.async.request-timeout=45000

logging.level.com.netflix.graphql.dgs=INFO
logging.level.org.springframework.web=info
logging.level.org.springframework.http=info
logging.level.org.springframework.graphql=info
logging.level.reactor.netty=info
