/*
 * Copyright 2026 IVIR Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ivir.devpackage.model.enums;

public enum BodyLocationCoarseEnum {
    ANTERIOR_ABDOMEN_LEFT_LOWER_QUADRANT,
    ANTERIOR_ABDOMEN_LEFT_UPPER_QUADRANT,
    ANTERIOR_ABDOMEN_RIGHT_LOWER_QUADRANT,
    ANTERIOR_ABDOMEN_RIGHT_UPPER_QUADRANT,
    ANTERIOR_GENITALS,
    ANTERIOR_HEAD_FACE,
    ANTERIOR_LEFT_ANKLE_FOOT,
    ANTERIOR_LEFT_FORE_ARM,
    ANTERIOR_LEFT_KNEE,
    ANTERIOR_LEFT_LATERAL_HEAD_FACE,
    ANTERIOR_LEFT_LOWER_LEG,
    ANTERIOR_LEFT_LOWER_THORAX,
    ANTERIOR_LEFT_PELVIS,
    ANTERIOR_LEFT_SHOULDER,
    ANTERIOR_LEFT_THIGH,
    ANTERIOR_LEFT_UPPER_ARM,
    ANTERIOR_LEFT_UPPER_THORAX,
    ANTERIOR_LEFT_WRIST_HAND,
    ANTERIOR_NECK,
    ANTERIOR_RIGHT_ANKLE_FOOT,
    ANTERIOR_RIGHT_FORE_ARM,
    ANTERIOR_RIGHT_KNEE,
    ANTERIOR_RIGHT_LATERAL_HEAD_FACE,
    ANTERIOR_RIGHT_LOWER_LEG,
    ANTERIOR_RIGHT_LOWER_THORAX,
    ANTERIOR_RIGHT_PELVIS,
    ANTERIOR_RIGHT_SHOULDER,
    ANTERIOR_RIGHT_THIGH,
    ANTERIOR_RIGHT_UPPER_ARM,
    ANTERIOR_RIGHT_UPPER_THORAX,
    ANTERIOR_RIGHT_WRIST_HAND,
    ANTERIOR_STERNUM,
    NOT_APPLICABLE,
    POSTERIOR_HEAD,
    POSTERIOR_LEFT_ANKLE_FOOT,
    POSTERIOR_LEFT_BUTTOCKS,
    POSTERIOR_LEFT_FLANK,
    POSTERIOR_LEFT_FORE_ARM,
    POSTERIOR_LEFT_KNEE,
    POSTERIOR_LEFT_LOWER_LEG,
    POSTERIOR_LEFT_LOWER_THORAX,
    POSTERIOR_LEFT_SHOULDER,
    POSTERIOR_LEFT_THIGH,
    POSTERIOR_LEFT_UPPER_ARM,
    POSTERIOR_LEFT_UPPER_THORAX,
    POSTERIOR_LEFT_WRIST_HAND,
    POSTERIOR_LOWER_LUMBAR_COCCYX_SPINE,
    POSTERIOR_MIDDLE_THORACIC_SPINE,
    POSTERIOR_NECK,
    POSTERIOR_RIGHT_ANKLE_FOOT,
    POSTERIOR_RIGHT_BUTTOCKS,
    POSTERIOR_RIGHT_FLANK,
    POSTERIOR_RIGHT_FORE_ARM,
    POSTERIOR_RIGHT_KNEE,
    POSTERIOR_RIGHT_LOWER_LEG,
    POSTERIOR_RIGHT_LOWER_THORAX,
    POSTERIOR_RIGHT_SHOULDER,
    POSTERIOR_RIGHT_THIGH,
    POSTERIOR_RIGHT_UPPER_ARM,
    POSTERIOR_RIGHT_UPPER_THORAX,
    POSTERIOR_RIGHT_WRIST_HAND,
    POSTERIOR_UPPER_CERVICAL_SPINE
}
